### ISSUE TITLE
Very sorry to be posting again, but I cant seem to format the printer correctly.

### ISSUE THREAD

**Issue by doobersn** [Kyle-Falconer/dymo-cups-drivers#3]
So I got it all set up, thanks to you! And I added the printer to my system by discovering it via the printer finding function in Windows 10. But...I cant seem to format it correctly. I cant get it to print 4x6, it only allows me to choose letter or a4 in the format options under printer preferences. I can print a test page via CUPS and that works fine, but if I print via windows (which is the only way I print) it doesnt print right. Any thoughts? I've very sorry to have to bother you again!

**Comment by Kyle-Falconer** [comment]
I think you'll need to also install the DYMO drivers for Windows on your Windows computer. Right now your Windows box is looking at the DYMO as a generic printer.

It should be on this page:
http://www.dymo.com/en-US/labelwriter-4xl-label-printer#tabContainer

**Comment by doobersn** [comment]
Kyle, just wanted to let you know I FINALLY figured this out. It wasn't the lack of Dymo drivers--those I already had (you definitely need them though). You cant choose the Dymo/Pi printer that Windows automatically finds ("Dymo LabelWriter 4XL @ raspberry pi"). Instead, you have to go to 'select a shared printer by name' and type in the address that you get when you click your Dymo printer in CUPS (which is https://yourIP:port#/printers/DYMO_LabelWriter_4XL) but MAKE SURE to get rid of the 's' in https--it must be http. 

Im super tired of dealing with this but very happy I figured it out and can't thank you enough. You didn't need to help or even respond to me and it's very much appreciated that you did. I hope this helps someone in the future!

**Comment by Kyle-Falconer** [comment]
You're quite welcome, and thanks for posting the solution as well. I'm sure it'll help someone.
